### PR TITLE
Spanish translation to prepare 1.2.0.0 release

### PR DESCRIPTION
**Pull request by angelborroy**
Only `master` branch seems to be available.

### CODE REVIEW

**Comment by AFaust** [comment]
Thanks @angelborroy . Do you maybe have time to look over the Share and webscript specific i18n resources? I.e. `/support-tools-repo/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/rendition-service2-localTransform-logs.get_es.properties`, `/support-tools-repo/src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/transform.get_es.properties`, or `/support-tools-share/src/main/resources/alfresco/messages/ootbee-support-tools_es.properties` (in the last one, I'd also have a question about consistency between the name for JS Console in Spanish: should it be Consola JavaScript everywhere?).

**Comment by angelborroy** [comment]
I guess that now I covered everything, but let me know if I missed something.

Spanish developers use that "Consola JavaScript" term to identify the JS Console from many years ago. But using "JS Console" is also an option.

**Comment by angelborroy** [comment]
I've created a new one in PR #199, not sure how to squash commits in this branch/PR.

**Comment by AFaust** [comment]
For future reference, squashing can be done by executing `git rebase -i upstream/master` (assuming that upstream is the alias of the OOTBee Support Tools remote repository), and marking all but the latest commit for being squashed. Afterwards, a `git push origin <branchName> --force` would update the PR branch with the squashed commit.

**Pull request closed without merging**
