### PR TITLE
Minor fixes before 1.2.0.0 release

### PR DESCRIPTION
**Pull request by hi-ko**
### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

minor fixes:
* doc menu links in javascript console pointing to /community are broken. 
* umlaut typo in german translation

### CODE REVIEW

**Comment by AFaust** [comment]
Is there actually any difference in script / services API that the obsolete 5.0 docs highlight / support? I was considering to link those old resources during cleanup but originally decided against it since some of the pages were so broken due to formatting that even the code samples were unusable. Unfortunately for the XPath / CMIS search / WebScript reference there weren't any alternatives, so I had to include the links to obsolete content.

**Comment by hi-ko** [comment]
> obsolete 5.0 docs 

Ah - you mean [Alfresco Repository JavaScript API reference](https://github.com/Alfresco/docs-alfresco/blob/master/_archive/content-services/5.0/concepts/API-JS-intro.md) in the archived 5.0 doc? I forgot about that. To be honest, I find the fragmented structure even more confusing than the old wiki pages . An alternative would be the takeover/revision into new wiki pages. e.g. as a new repo here in OrderOfTheBee home. Anyhow, we should include either links to the somehow broken wiki or to the archived doc pages since it is quite hard to find any Alfresco related JS docs.

**Comment by AFaust** [comment]
No, my question was only if there is actually anything at all in the 5.0 APIs as documented (in either obsolete wiki or official docs) that is different from current JavaScript API and root objects. The whole ACS JavaScript API has been rather stable / stagnant for a while now and if there is not a feature difference in the API that any old docs highlight, then I wonder what the purpose for linking would be. I just haven't checked myself yet in too much detail and months ago dismissed it more out of hand rather than after a thorough comparison, so I was wondering if you had specific differences in mind / that you noticed that are important.
With regards to the cookbook I can see the reason in those many samples, though they are extremely broken due to formatting issues after the two-times wiki migration.

**Comment by hi-ko** [comment]
In current documentation, there is no JavaScript API except that minimalistic root objects list, or have I overlooked something? It's not for me and not for you but I guess most admins using JS-console would be happy to get at least something like archived reference pages or obsolete wiki pages to have complete api doc with examples.

**Comment by hi-ko** [comment]
I just got the idea to incude these links because a customer asked me to assist him to find documentation and examples about the repo java script-api. Google only finds the ADF related alfresco-js-api, which is not what you are looking for working in the js-console ...

**Pull request merged**
