### PR TITLE
Implemented the methods to start, stop and restart subsystems instances;

### PR DESCRIPTION
**Pull request by douglascrp**
### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

This PR implements the feature described in #156 

### RELATED INFORMATION

Fixes #

# BE WARNED

- If any of the checklist items are missed, incomplete or invalid we will not accept the PR
- If you are not responsive to feedback on your PR we will not accept the PR
- If we do not accept your PR we will provide feedback on the PR indicating why
- After some time, we will close PRs that have not been accepted

When we decline or close your PR. You are encouraged to address the concerns outlined in the
PR and then re-submit it. We want contributions. We also need for them to be of high quality
and high value and to not take undue resources away from the features and enhancements the
core team is working on. Thanks for understanding!

### CODE REVIEW

**Comment by AFaust** [comment]
Too bad you did not allow commits on your feature branch from reviewers. I was about to add German localisation for the PR. But since I found some other lacking German localisations in the command console, I'll have to create a separate PR anyway.

So, even though it took way too long for me to get to it, this PR will now be merged.

**Comment by douglascrp** [comment]
@AFaust About the "not allow commits on your feature branch from reviewers", I have no idea how to do that, but I would like to learn about it... any hint?

**Comment by AFaust** [comment]
It is an option / checkbox when you create the PR that needs to be set. I believe GitHub remembers the setting from previous PRs (either globally or only in the same project).

**Comment by douglascrp** [comment]
@AFaust Awesome... I will pay attention to that next time.
Thank you

**Pull request merged**
