### PR TITLE
Create CODE_OF_CONDUCT.md

### LINKED ISSUE #23: Add a code of conduct to the project
Unless folks object, I plan to start from: http://contributor-covenant.org/

Documentation is here: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

### PR DESCRIPTION
**Pull request by binduwavell**
resolves #23

### CODE REVIEW

**Comment by binduwavell** [comment]
Maybe I should update the README with a link to this?

**Comment by binduwavell** [comment]
@ahmedowian will you review and propose any updates related to your request earlier?

**Comment by binduwavell** [comment]
I updated the README and specifically added the Cussing / swearing text as an example of inappropriate behavior.

**Comment by binduwavell** [comment]
BTW, the commits for the PR were done through the Github UI as such the commits are a bit messy. I would expect these to be squashed if/when they are merged.

**Comment by ahmedowian** [comment]
Also, 

> Before adopting the Contributor Covenant take the time to discuss and decide how to deal with problems as they emerge. Document the policy and procedure for enforcement, and add it to your README or in another visible, appropriate place. Consider if your project team has the willingness and maturity to follow through on your enforcement procedures.

**Comment by AFaust** [comment]
As far as I can see, the MIT license information on the home page is outdated - the license in the [GitHub project](https://github.com/ContributorCovenant/contributor_covenant/) from which version 1.4 was built is a different one.

**Comment by AFaust** [comment]
In terms of maturity / willingness to deal with enforcement, I have little doubt that we can manage that - both within the team itself, as well - if all else fails - as part of Order of the Bee. Final escalation could always be handed off to the board via the ADDONS chair (myself currently).

**Comment by binduwavell** [comment]
@AFaust given our current project maturity I completely agree with your assertion about managing enforcement. If things go sideways we may have to make some difficult decisions publicly, but given past experience with folks in the Order I seriously doubt it will come to anything like that. I honestly think the worst that could happen is a fork.

**Pull request merged**
