### PR TITLE
Suspension of scheduled job triggers

### LINKED ISSUE #113: Add ability to suspend scheduled job triggering in Scheduled Jobs tools
## FEATURE / ENHANCEMENT

During a training at Xenit this idea came up from a prospective administrator. In some situations, it may be beneficial to temporarily suspend the triggering of scheduled jobs (or potentially even reschedule them). Since we already access the scheduler to display trigger details, we should investigate the option of adding actions to suspend / modify those triggers. Even when the trigger is disabled, it should still be possible to manually trigger a job in the UI.

### PR DESCRIPTION
**Pull request by AFaust**
### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

This PR adds the ability to suspend/resume triggers of scheduled jobs at runtime. This change comes with added data in the UI regarding the trigger identity and state, which technically no longer lists scheduled jobs but triggers for scheduled jobs (in Alfresco we typically have a 1:1 relation of trigger to job).

L10n bundles for all currently provided locales have been enhanced with the new message keys though proper translation is left to experts within our community (i.e. @angelborroy, @douglascrp, @iwkse) after this PR has been merged.

### RELATED INFORMATION

Fixes #113

### CODE REVIEW

**Comment by AFaust** [comment]
PR will need to be rebased once #121 has been merged to integrate the changes to scheduled jobs from the adaption to Alfresco 6.0

**Comment by yregaieg** [comment]
Can't fin in the commit log/code anything suggesting special treatment for ACS 6.0.
Is the same implementation still valid for ACS 6.0 or did we miss something ?

**Comment by AFaust** [comment]
The commit log does not contain an explicit mention, but everywhere you see a
```javascript
quartzMajorVersion === 1 
```
involved you know there is specific treatment for the ACS pre-6.0/6.0 distinction.

**Comment by yregaieg** [comment]
indeed, sorry for missing that ...

**Comment by AFaust** [comment]
Squashed and merged - now we are back at 0 open pull requests and can start working on the new features / additions.

**Pull request merged**
