### PR TITLE
Prepare release 1.1.0.0

### PR DESCRIPTION
**Pull request by AFaust**
### CHECKLIST

We will not consider a PR until the following items are checked off--thank you!

- [x] There aren't existing pull requests attempting to address the issue mentioned here
- [x] Submission developed in a feature branch--not master

### CONVINCING DESCRIPTION

This PR simply prepares the release of 1.1.0.0 by updating the version numbers in Maven POMs.

### RELATED INFORMATION

 None

### CODE REVIEW

**Comment by yregaieg** [comment]
@AFaust Can we include support for deployment as Alfresco Simple Module (aka jar) in this release as well ?

**Comment by AFaust** [comment]
@yregaieg If you have the time to wrestle with SDK to make this work, why not. If that requires an SDK update, I would require that after the upgrade, we are still able to build a proper javadoc, sources and classes JAR ("proper" classes JAR means without static files) and that almost none of the structure changes (if change is necessary, it should simplify the structure, not be a net addition).

**Comment by yregaieg** [comment]
Ok, If you do not mind, I would love to have a shot on it later today before we release 1.1.0.0, I will assign the PR to you for review, the change should be as simple as moving files around from amp/config directory to resources directory and from amp/web to resources/META-INF. No SDK upgrade needed!

**Comment by AFaust** [comment]
Oh - I should have been more clear / detailed. I would also require that the content of the AMPs not change. So having a simple JAR is fine, but it should have no impact on the AMP...

**Comment by yregaieg** [comment]
@AFaust that's not possible, we would need to move some files from being directly under the amp to be included in the jar. So we would still have an amp, but only/mainly as a wrapper for the jar

**Comment by binduwavell** [comment]
Axel asked me if I was tracking this thread. I was not. I’ve read through it twice and I’m not sure I grok the last little bit about the AMP not changing. 

What is in the AMP that is not in the JAR?

I’ll have to review how SDK 3 makes AMPs. My recollection is that it pulls a couple config files out of the JAR and moves them into the AMP, but generally without other JAR does it just is a wrapper for the slightly modified JAR and the standalone JAR should be complete.

**Comment by AFaust** [comment]
The AMP contains configuration, web script files and client-side resources that are not packaged into the JAR at the moment. As far as I know (bear in mind I do not use SDK 3+ for any projects, and this would likely be the only one for me) any update and switch to enable JAR build would mean that those files would always be part of the JAR, and the AMP would be nothing more than a JAR wrapper.

On a side note: I started local testing with Alfresco 6.1.2 GA and on the repository tier it looks to be fully compatible (don't expect many issues on Share due to product stagnation). Though I am still confused as to how they managed to achieve Java 9+ compatibility with all the legacy libraries (like ACEGI Security) still included and unchanged, which did wreak havoc when I tested Alfresco 5.2 with Java 9 in 2017.

**Comment by binduwavell** [comment]
If we have WebScript files outside of jar we should be able to love them into jar so AMP is just a JAR wrapper with a module.properties.

**Comment by AFaust** [comment]
That is specifically what I personally would like to avoid. I am perfectly happy building a separate/dedicated JAR that complies with the Simple Alfresco Module concept, but that should not force the AMP to change, which should still contain static files as before.

**Comment by yregaieg** [comment]
I think pushing the update branch button wasn't a good call after all... it created a merge commit from master into the release branch :/

**Comment by AFaust** [comment]
The history is clean - the diffs are identical between my local branch and the remote one you update. So perfectly fine. Will merge that, build / publish a release and work on some wiki updates.

**Pull request merged**
