### PR TITLE
Enable tools for all editions and avoid confusion with default tools via unique menu group (#29)

### PR DESCRIPTION
**Pull request by AFaust**
This PR addresses #29 and enables all tools for any edition of Alfresco. Renaming the web script package and providing a label for that avoids any confusion in the UI with either the bundled Support Tools (EE 5.2+) or the installable addon (EE 5.1).

### CODE REVIEW

**Comment by AFaust** [comment]
Due to extensive structure changes in #37 this should not be merged before #37 is merged and this PR could be rebased on top of that.

**Comment by binduwavell** [comment]
@AFaust I believe I resolved the conflict here, could you take a look at my commit on the PR and see what you think?

**Comment by binduwavell** [comment]
@AFaust I'm very sorry I've made a mess of this. I attempted to use the GitHub UI to merge this PR with master as it had diverged.

GitHub indicated there was a single conflicting file. I figured out how to resolve the issues in that file. I then attempted to build the resulting branch and it failed. In investigated and it appeared that the GitHub merge strategy was pretty flawed in this case.

I then force pushed your enable-enterprise branch without that broken merge and it closed this PR?! I believe your branch is fine and still needs to be merged/rebased. I could have made a new PR request on your behalf, but given how confusing this stuff is working in someone elses branch. I'm throwing in the towel at least for tonight.

Again, I'm sorry for having botched the PR and fingers crossed it will be nice an easy for you as the branch owner to rebase or merge and then re-create the PR.

**Comment by binduwavell** [comment]
@AFaust  I was wrong, I completely messed up YOUR branch.

I'm feeling pretty damn terrible right now. From the comment history you can see me melting down on this PR. I'm so sorry. I recovered the lost commits. Attempted to push them back to your fork which was blocked since the PR isn't associated with your branch any more.

So I pushed the recovered commits to my fork and created PR #39 with them. We still need to rebase or merge master. 

You could simply push --force what you have cached locally on your branch and things will be better for you or you can pull the info from this new PR.

Given that I've messed stuff up so badly I don't want to work on this tonight in the event that I make things much worse.

Again, I'm terribly sorry.

**Comment by AFaust** [comment]
Ok - the branch has been reconstituted from my local clone and rebased to current master with the necessary changes. The result has been build successfully and tested locally.

**Comment by binduwavell** [comment]
Here is the project I tested with:

[ootbentalf.zip](https://github.com/OrderOfTheBee/ootbee-support-tools/files/702249/ootbentalf.zip)

**Comment by AFaust** [comment]
Adding the README update finally triggered Travis CI build which seemed to have been stuck after the failure in the history.

**Pull request merged**
